include:
  - apache.install
  - apache.mod.ssl
  - apache.cert.star-entrata-com
  - apache.mod.php
  - apache.mod.rewrite
  - apache.vhost.satis
  - satis.ppa-repo
  - php.install
  - satis.satis-user
  - satis.directories
  - satis.dependencies
  - satis.composer-install
  - satis.satis-install
  - satis.authfile
  - satis.config
  - satis.internal_dns
